### ISSUE TITLE
[1pt] - New Rails App

### ISSUE THREAD

**Issue by lucabenaventew** [lucabenaventew/ror-capstone#11]
- Create a new Rails app and init the repo.

**Comment by AmaduKamara** [comment]
# Invalid Submission ❌❌❌ 

Hi @lucabenaventew,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow due requirements. Kindly add the link to the GitHub Issue that has a link to GitHub projects and information of the group members all mentioned in your PR description. Kindly work on that so your project can be reviewed 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```
